import { Patient } from '../types/triage';
import { Facility, UserProfile } from '../types/roles';

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    name: 'City Community Health Center',
    code: 'CHC-OD-0412',
    type: 'CHC',
    district: 'Khordha',
    state: 'Odisha',
    activePatients: 48,
  },
  {
    id: 'fac-2',
    name: 'District Hospital Cuttack',
    code: 'DH-OD-0021',
    type: 'DISTRICT_HOSPITAL',
    district: 'Cuttack',
    state: 'Odisha',
    activePatients: 114,
  },
  {
    id: 'fac-3',
    name: 'PHC Chandpur Rural Clinic',
    code: 'PHC-OD-0108',
    type: 'PHC',
    district: 'Nayagarh',
    state: 'Odisha',
    activePatients: 19,
  },
  {
    id: 'fac-4',
    name: 'Bhubaneswar Industrial Health Unit',
    code: 'IHU-OD-0089',
    type: 'INDUSTRIAL_HEALTH_UNIT',
    district: 'Khordha',
    state: 'Odisha',
    activePatients: 32,
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Dr. A. Sharma',
    role: 'DOCTOR',
    title: 'Medical Officer',
    facility: 'City Community Health Center',
    department: 'General Medicine & Triage',
    registrationNumber: 'MCI-2015-84920',
  },
  {
    id: 'user-2',
    name: 'Sunita Biswal',
    role: 'NURSE',
    title: 'Staff Nurse Grade-I',
    facility: 'City Community Health Center',
    department: 'Outpatient Triage',
  },
  {
    id: 'user-3',
    name: 'Ramesh Sahoo',
    role: 'HEALTH_WORKER',
    title: 'Community Health Officer (CHO)',
    facility: 'City Community Health Center',
    department: 'Primary Health Services',
  },
  {
    id: 'user-4',
    name: 'Meera Jena (Patient)',
    role: 'PATIENT',
    title: 'Citizen',
    facility: 'City Community Health Center',
  },
  {
    id: 'user-5',
    name: 'Admin Desk',
    role: 'ADMIN',
    title: 'Health Systems Administrator',
    facility: 'City Community Health Center',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'P-1042',
    syntheticCode: 'SYN-2026-001',
    name: 'Meera Jena',
    age: 28,
    gender: 'Female',
    primaryLanguage: 'Odia (ଓଡ଼ିଆ)',
    translatedToEnglish: true,
    contactMasked: '+91 94*** **102',
    visitId: 'VST-2026-8942',
    arrivalTime: '12 Aug 2026 · 09:12',
    chiefComplaint: 'Acute shortness of breath with high fever for 3 days and progressive fatigue',
    symptoms: [
      {
        id: 'sym-1',
        name: 'Shortness of breath',
        duration: '1 day',
        severity: 'SEVERE',
        onset: 'Sudden, aggravated on lying down',
        notes: 'Noticeable tachypnea during speech input',
        source: 'VOICE',
        confidence: 0.98,
      },
      {
        id: 'sym-2',
        name: 'High fever',
        duration: '3 days',
        severity: 'MODERATE',
        onset: 'Gradual onset with chills',
        source: 'VOICE',
        confidence: 0.96,
      },
      {
        id: 'sym-3',
        name: 'Persistent dry cough',
        duration: '3 days',
        severity: 'MODERATE',
        source: 'VOICE',
        confidence: 0.92,
      },
      {
        id: 'sym-4',
        name: 'General fatigue & headache',
        duration: '3 days',
        severity: 'MODERATE',
        source: 'VOICE',
        confidence: 0.94,
      },
    ],
    relevantHistory: [
      'No documented history of bronchial asthma or COPD',
      'No known allergy to beta-lactam antibiotics',
      'Completed 2 primary doses of COVID-19 vaccination (2022)',
      'Lives in urban community cluster with reported seasonal flu',
    ],
    vitals: {
      bloodPressure: '118/76 mmHg',
      pulseRate: '104 bpm (tachycardia)',
      temperature: '102.4 °F',
      spO2: '91% on room air',
      respiratoryRate: '26 breaths/min',
    },
    facts: [
      {
        id: 'fact-1',
        category: 'LAB_CBC',
        name: 'Hemoglobin',
        value: '11.2',
        unit: 'g/dL',
        referenceRange: '12.0 - 15.5 g/dL',
        sourceDocument: 'CBC_Report_P1042.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 1',
        confidence: 'HIGH',
        confidenceScore: 0.98,
        boundingBox: { x: 12, y: 34, width: 76, height: 5 },
      },
      {
        id: 'fact-2',
        category: 'LAB_CBC',
        name: 'WBC Count (TLC)',
        value: '13,800',
        unit: '/µL',
        referenceRange: '4,000 - 10,000 /µL',
        sourceDocument: 'CBC_Report_P1042.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 2',
        confidence: 'HIGH',
        confidenceScore: 0.97,
        boundingBox: { x: 12, y: 40, width: 76, height: 5 },
      },
      {
        id: 'fact-3',
        category: 'LAB_CBC',
        name: 'Platelet Count',
        value: '2.1',
        unit: 'lakh/µL',
        referenceRange: '1.5 - 4.5 lakh/µL',
        sourceDocument: 'CBC_Report_P1042.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 3',
        confidence: 'HIGH',
        confidenceScore: 0.99,
        boundingBox: { x: 12, y: 46, width: 76, height: 5 },
      },
      {
        id: 'fact-4',
        category: 'LAB_BIOCHEM',
        name: 'Blood Sugar (Random)',
        value: '112',
        unit: 'mg/dL',
        referenceRange: '70 - 140 mg/dL',
        sourceDocument: 'Biochem_Report_P1042.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 1',
        confidence: 'HIGH',
        confidenceScore: 0.95,
        boundingBox: { x: 12, y: 55, width: 76, height: 5 },
      },
      {
        id: 'fact-5',
        category: 'VITALS',
        name: 'SpO₂ Oxygen Saturation',
        value: '91',
        unit: '%',
        referenceRange: '95 - 100 %',
        sourceDocument: 'Vitals_Intake_Slip.pdf',
        sourcePage: 1,
        sourceLocation: 'Box 2 (Vitals)',
        confidence: 'HIGH',
        confidenceScore: 0.96,
        boundingBox: { x: 12, y: 64, width: 76, height: 5 },
      },
    ],
    missingInfo: [
      {
        id: 'miss-1',
        field: 'spO2_repeat',
        label: 'Repeat SpO₂ & Oxygen Flow Check',
        category: 'VITALS',
        status: 'PARTIALLY_KNOWN',
        reason: 'Initial reading 91% indicates borderline hypoxemia; repeat probe reading needed before OPD handoff.',
        askPrompt: 'Has patient rested for 5 minutes before current pulse oximeter check?',
        quickOptions: ['Rested > 5 mins', 'Cold extremities', 'Movement artifact', 'Confirmed 91%'],
      },
      {
        id: 'miss-2',
        field: 'respiratory_rate',
        label: 'Auscultation / Wheeze Presence',
        category: 'EXAM',
        status: 'NOT_PROVIDED',
        reason: 'Physical chest sounds not yet recorded by triage nurse.',
        askPrompt: 'Are there audible wheezing or crackles on normal respiration?',
        quickOptions: ['Clear', 'Bilateral crackles', 'Expiratory wheeze', 'Reduced breath sounds'],
      },
      {
        id: 'miss-3',
        field: 'chest_pain',
        label: 'Pleuritic Chest Pain',
        category: 'SYMPTOM_DETAIL',
        status: 'PARTIALLY_KNOWN',
        reason: 'Patient reported chest tightness in voice intake; clarify if sharp or pleuritic.',
        askPrompt: 'Does chest pain intensify on taking a deep breath or coughing?',
        quickOptions: ['Yes, sharp pain', 'No, dull tightness only', 'No chest discomfort'],
      },
    ],
    riskFlags: [
      {
        id: 'rf-1',
        type: 'RESPIRATORY_CONCERN',
        severity: 'POTENTIAL_URGENCY',
        label: 'Potential urgency signal: Respiratory Concern',
        description: 'Shortness of breath reported alongside SpO₂ of 91% and elevated leukocytosis (13,800/µL). Worsening over 3-day window.',
        evidenceFactIds: ['fact-2', 'fact-5'],
        missingFactNames: ['Repeat SpO₂ confirmation', 'Chest auscultation findings'],
        humanActionRequired: true,
      },
    ],
    aiQuestions: [
      {
        id: 'q-1',
        missingInfoId: 'miss-1',
        questionText: 'Are you experiencing difficulty breathing when lying down flat?',
        questionTextIndic: {
          odia: 'ଆପଣ ଚିତ୍ ହୋଇ ଶୋଇବା ସମୟରେ ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ ଅନୁଭବ କରୁଛନ୍ତି କି?',
          hindi: 'क्या आपको सीधे लेटने पर सांस लेने में कठिनाई हो रही है?',
        },
        options: ['Yes', 'No', 'Not sure'],
      },
      {
        id: 'q-2',
        missingInfoId: 'miss-3',
        questionText: 'When did the shortness of breath acutely worsen?',
        questionTextIndic: {
          odia: 'ନିଶ୍ୱାସ ନେବାର କଷ୍ଟ କେବେଠାରୁ ଅଧିକ ବଢ଼ିଗଲା?',
          hindi: 'सांस फूलने की समस्या कब से अधिक बढ़ गई?',
        },
        options: ['Today morning', '1–2 days ago', 'More than 2 days ago', 'Not sure'],
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        timestamp: '12 Aug · 09:12',
        title: 'Patient voice intake recorded in Odia',
        description: 'Patient described high fever, headache, and progressive dry cough for 3 days.',
        source: 'VOICE',
        actor: 'Patient Meera Jena',
        details: 'Language: Odia (ଓଡ଼ିଆ), 48s duration, transcribed with 97% confidence.',
      },
      {
        id: 'tl-2',
        timestamp: '12 Aug · 09:14',
        title: 'Speech transcription & translation created',
        description: 'Native Odia text converted and translated to English clinical schema.',
        source: 'AI_DRAFT',
        actor: 'SwasthyaSetu Multimodal Engine',
      },
      {
        id: 'tl-3',
        timestamp: '13 Aug · 10:20',
        title: 'CBC & Biochemistry lab report uploaded',
        description: 'Document CBC_Report_P1042.pdf attached and processed via OCR engine.',
        source: 'REPORT',
        actor: 'CHO Ramesh Sahoo',
        details: 'Extracted 5 structured parameters with high confidence.',
      },
      {
        id: 'tl-4',
        timestamp: '14 Aug · 11:45',
        title: 'Symptoms reported as worsening',
        description: 'Patient noted acute onset of shortness of breath upon walking to facility.',
        source: 'REVIEWER',
        actor: 'Staff Nurse Sunita B.',
      },
      {
        id: 'tl-5',
        timestamp: '14 Aug · 11:46',
        title: 'Potential urgency signal tagged',
        description: 'Advisory flag: Respiratory concern triggered based on SpO₂ 91% and dyspnea.',
        source: 'AI_DRAFT',
        actor: 'SwasthyaSetu Triage Engine',
      },
    ],
    auditLog: [
      {
        id: 'aud-1',
        timestamp: '14 Aug · 11:42',
        actor: 'Meera Jena',
        actorRole: 'Patient',
        action: 'SUBMIT_VOICE_INTAKE',
        objectAffected: 'AudioRecord #AUD-9104',
        details: 'Submitted 48-second Odia audio recording from Community Health Kiosk.',
      },
      {
        id: 'aud-2',
        timestamp: '14 Aug · 11:43',
        actor: 'SwasthyaSetu Engine',
        actorRole: 'AI_AGENT',
        action: 'TRANSCRIBE_TRANSLATE',
        objectAffected: 'Transcript #TRN-811',
        details: 'Generated Odia transcript and English translation.',
      },
      {
        id: 'aud-3',
        timestamp: '14 Aug · 11:43',
        actor: 'SwasthyaSetu OCR',
        actorRole: 'AI_AGENT',
        action: 'REPORT_EXTRACTION',
        objectAffected: 'Document #DOC-CBC-1042',
        details: 'Extracted Hb, WBC, Platelets, Sugar from CBC_Report_P1042.pdf.',
      },
      {
        id: 'aud-4',
        timestamp: '14 Aug · 11:44',
        actor: 'SwasthyaSetu Triage Engine',
        actorRole: 'AI_AGENT',
        action: 'GENERATE_TRIAGE_DRAFT',
        objectAffected: 'Patient Note P-1042',
        details: 'Compiled structured advisory summary and detected 3 missing fields.',
      },
      {
        id: 'aud-5',
        timestamp: '14 Aug · 11:45',
        actor: 'Dr. A. Sharma',
        actorRole: 'Medical Officer',
        action: 'OPEN_CASE_WORKSPACE',
        objectAffected: 'Patient Note P-1042',
        details: 'Case opened for clinical review in Primary Queue.',
      },
    ],
    status: 'PENDING_REVIEW',
    priority: 'RED',
    facilityId: 'fac-1',
  },
  {
    id: 'P-1035',
    syntheticCode: 'SYN-2026-002',
    name: 'Rajesh Kumar',
    age: 45,
    gender: 'Male',
    primaryLanguage: 'Hindi (हिन्दी)',
    translatedToEnglish: true,
    contactMasked: '+91 98*** **389',
    visitId: 'VST-2026-8935',
    arrivalTime: '14 Aug 2026 · 10:45',
    chiefComplaint: 'Epigastric burning pain radiating to retrosternal area with nausea for 2 days',
    symptoms: [
      {
        id: 'sym-201',
        name: 'Epigastric pain',
        duration: '2 days',
        severity: 'MODERATE',
        onset: 'Postprandial, worse after spicy meal',
        source: 'MANUAL',
        confidence: 0.95,
      },
      {
        id: 'sym-202',
        name: 'Nausea & bloating',
        duration: '2 days',
        severity: 'MILD',
        source: 'MANUAL',
        confidence: 0.93,
      },
    ],
    relevantHistory: [
      'Occasional dyspepsia treated with OTC antacids',
      'No history of ischemic heart disease or diabetes mellitus',
      'Non-smoker, occasional tea consumption',
    ],
    vitals: {
      bloodPressure: '124/82 mmHg',
      pulseRate: '78 bpm',
      temperature: '98.6 °F',
      spO2: '98% on room air',
      respiratoryRate: '16 breaths/min',
    },
    facts: [
      {
        id: 'fact-201',
        category: 'LAB_BIOCHEM',
        name: 'Blood Sugar (Fasting)',
        value: '98',
        unit: 'mg/dL',
        referenceRange: '70 - 100 mg/dL',
        sourceDocument: 'Biochem_Report_P1035.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 2',
        confidence: 'HIGH',
        confidenceScore: 0.97,
        boundingBox: { x: 12, y: 38, width: 76, height: 5 },
      },
      {
        id: 'fact-202',
        category: 'LAB_BIOCHEM',
        name: 'Serum Amylase',
        value: '64',
        unit: 'U/L',
        referenceRange: '28 - 100 U/L',
        sourceDocument: 'Biochem_Report_P1035.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 5',
        confidence: 'MEDIUM',
        confidenceScore: 0.88,
        boundingBox: { x: 12, y: 52, width: 76, height: 5 },
      },
    ],
    missingInfo: [
      {
        id: 'miss-201',
        field: 'cardiac_radiation',
        label: 'Radiation to Left Arm or Jaw',
        category: 'SYMPTOM_DETAIL',
        status: 'NOT_PROVIDED',
        reason: 'Required to rule out atypical angina in 45-year-old male with retrosternal burning.',
        askPrompt: 'Does the pain spread to your left shoulder, left arm, neck, or jaw?',
        quickOptions: ['No radiation', 'Yes to left shoulder', 'Yes to jaw', 'Not sure'],
      },
      {
        id: 'miss-202',
        field: 'ecg_status',
        label: '12-Lead Baseline ECG',
        category: 'INVESTIGATION',
        status: 'NOT_PROVIDED',
        reason: 'Baseline ECG recommended at primary triage for retrosternal symptoms.',
        askPrompt: 'Has an ECG been performed today at the health center?',
        quickOptions: ['ECG done - normal', 'ECG done - awaiting review', 'Not yet done'],
      },
    ],
    riskFlags: [
      {
        id: 'rf-201',
        type: 'CHEST_DISCOMFORT',
        severity: 'PROMPT_REVIEW',
        label: 'Needs attention: Atypical chest/epigastric discomfort',
        description: 'Age 45 male with 2-day epigastric/retrosternal pain. Requires clinical discrimination between dyspepsia and acute coronary syndrome.',
        evidenceFactIds: ['fact-201'],
        missingFactNames: ['Radiation to left arm/jaw', '12-lead ECG'],
        humanActionRequired: true,
      },
    ],
    aiQuestions: [
      {
        id: 'q-201',
        missingInfoId: 'miss-201',
        questionText: 'Does the burning pain increase during physical exertion or walking upstairs?',
        questionTextIndic: {
          hindi: 'क्या चलने-फिरने या सीढ़ियां चढ़ने पर यह दर्द और बढ़ जाता है?',
        },
        options: ['No, stays same', 'Yes, worse on walking', 'Only after heavy meals', 'Not sure'],
      },
    ],
    timeline: [
      {
        id: 'tl-201',
        timestamp: '14 Aug · 10:45',
        title: 'Patient typed symptoms via kiosk',
        description: 'Rajesh entered epigastric discomfort, nausea, and indigestion symptoms.',
        source: 'MANUAL',
        actor: 'Patient Rajesh Kumar',
      },
      {
        id: 'tl-202',
        timestamp: '14 Aug · 10:47',
        title: 'Biochemistry report uploaded',
        description: 'Report uploaded by kiosk operator; fasting glucose & amylase extracted.',
        source: 'REPORT',
        actor: 'CHO Ramesh Sahoo',
      },
      {
        id: 'tl-203',
        timestamp: '14 Aug · 10:48',
        title: 'Missing information flagged',
        description: 'System identified missing cardiac radiation check and ECG recommendation.',
        source: 'AI_DRAFT',
        actor: 'SwasthyaSetu Engine',
      },
    ],
    auditLog: [
      {
        id: 'aud-201',
        timestamp: '14 Aug · 10:45',
        actor: 'Rajesh Kumar',
        actorRole: 'Patient',
        action: 'SUBMIT_MANUAL_INTAKE',
        objectAffected: 'IntakeForm #IN-778',
        details: 'Submitted symptom details via touch kiosk in Hindi.',
      },
      {
        id: 'aud-202',
        timestamp: '14 Aug · 10:48',
        actor: 'SwasthyaSetu Engine',
        actorRole: 'AI_AGENT',
        action: 'GENERATE_TRIAGE_DRAFT',
        objectAffected: 'Patient Note P-1035',
        details: 'Structured note drafted with Yellow priority pending ECG check.',
      },
    ],
    status: 'NEEDS_MORE_INFO',
    priority: 'YELLOW',
    facilityId: 'fac-1',
  },
  {
    id: 'P-1018',
    syntheticCode: 'SYN-2026-003',
    name: 'Ananya Das',
    age: 34,
    gender: 'Female',
    primaryLanguage: 'Bengali (বাংলা)',
    translatedToEnglish: true,
    contactMasked: '+91 97*** **991',
    visitId: 'VST-2026-8918',
    arrivalTime: '14 Aug 2026 · 08:30',
    chiefComplaint: 'Mild runny nose, sneezing, low-grade fever for 2 days',
    symptoms: [
      {
        id: 'sym-301',
        name: 'Coryza / runny nose',
        duration: '2 days',
        severity: 'MILD',
        source: 'VOICE',
        confidence: 0.97,
      },
      {
        id: 'sym-302',
        name: 'Low-grade feverish feeling',
        duration: '2 days',
        severity: 'MILD',
        source: 'VOICE',
        confidence: 0.95,
      },
      {
        id: 'sym-303',
        name: 'Mild sore throat',
        duration: '1 day',
        severity: 'MILD',
        source: 'VOICE',
        confidence: 0.94,
      },
    ],
    relevantHistory: [
      'Seasonal allergic rhinitis during monsoon change',
      'No chronic comorbidities',
    ],
    vitals: {
      bloodPressure: '116/74 mmHg',
      pulseRate: '72 bpm',
      temperature: '99.1 °F',
      spO2: '99% on room air',
      respiratoryRate: '15 breaths/min',
    },
    facts: [
      {
        id: 'fact-301',
        category: 'LAB_CBC',
        name: 'Hemoglobin',
        value: '12.8',
        unit: 'g/dL',
        referenceRange: '12.0 - 15.5 g/dL',
        sourceDocument: 'CBC_Report_P1018.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 1',
        confidence: 'HIGH',
        confidenceScore: 0.99,
        boundingBox: { x: 12, y: 34, width: 76, height: 5 },
      },
      {
        id: 'fact-302',
        category: 'LAB_CBC',
        name: 'WBC Count (TLC)',
        value: '6,200',
        unit: '/µL',
        referenceRange: '4,000 - 10,000 /µL',
        sourceDocument: 'CBC_Report_P1018.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 2',
        confidence: 'HIGH',
        confidenceScore: 0.98,
        boundingBox: { x: 12, y: 40, width: 76, height: 5 },
      },
      {
        id: 'fact-303',
        category: 'LAB_CBC',
        name: 'Platelet Count',
        value: '2.8',
        unit: 'lakh/µL',
        referenceRange: '1.5 - 4.5 lakh/µL',
        sourceDocument: 'CBC_Report_P1018.pdf',
        sourcePage: 1,
        sourceLocation: 'Table row 3',
        confidence: 'HIGH',
        confidenceScore: 0.98,
        boundingBox: { x: 12, y: 46, width: 76, height: 5 },
      },
    ],
    missingInfo: [],
    riskFlags: [],
    aiQuestions: [],
    timeline: [
      {
        id: 'tl-301',
        timestamp: '14 Aug · 08:30',
        title: 'Voice intake recorded in Bengali',
        description: 'Patient recorded symptoms of common seasonal viral upper respiratory tract symptoms.',
        source: 'VOICE',
        actor: 'Patient Ananya Das',
      },
      {
        id: 'tl-302',
        timestamp: '14 Aug · 08:35',
        title: 'Routine CBC report extracted',
        description: 'Parameters within normal physiological limits.',
        source: 'REPORT',
        actor: 'Staff Nurse Sunita B.',
      },
      {
        id: 'tl-303',
        timestamp: '14 Aug · 08:40',
        title: 'Assigned Green Routine Priority',
        description: 'Vital signs and blood counts stable; ready for standard general OPD review.',
        source: 'AI_DRAFT',
        actor: 'SwasthyaSetu Engine',
      },
    ],
    auditLog: [
      {
        id: 'aud-301',
        timestamp: '14 Aug · 08:30',
        actor: 'Ananya Das',
        actorRole: 'Patient',
        action: 'SUBMIT_VOICE_INTAKE',
        objectAffected: 'AudioRecord #AUD-9102',
        details: 'Submitted Bengali voice recording.',
      },
      {
        id: 'aud-302',
        timestamp: '14 Aug · 08:40',
        actor: 'SwasthyaSetu Engine',
        actorRole: 'AI_AGENT',
        action: 'GENERATE_TRIAGE_DRAFT',
        objectAffected: 'Patient Note P-1018',
        details: 'Routine priority draft generated.',
      },
    ],
    status: 'PENDING_REVIEW',
    priority: 'GREEN',
    facilityId: 'fac-1',
  },
];
