"""
Demo Handoff Provider.
"""

from __future__ import annotations

import asyncio
import uuid
from typing import Any

from careintel.infrastructure.handoff.port import DeliveryResult, HandoffProvider


class DemoHandoffProvider(HandoffProvider):
    """
    Deterministic demo provider for development.
    Always succeeds after a short delay.
    """

    async def deliver(
        self, package_content: dict[str, Any], recipient_config: dict[str, Any]
    ) -> DeliveryResult:
        # Simulate network delay
        await asyncio.sleep(0.5)

        # In a real demo, we might want to occasionally fail for testing.
        # But for now, we'll keep it deterministic and successful.

        # Simulate an external reference ID generated by the recipient system
        reference = f"DEMO-{uuid.uuid4().hex[:8].upper()}"

        return DeliveryResult(
            success=True,
            reference=reference,
        )
