"""
Case state definitions.
"""

from enum import StrEnum


class CaseState(StrEnum):
    """Lifecycle states for a Case."""

    CREATED = "CREATED"
    CONSENTED = "CONSENTED"
    INPUT_RECEIVED = "INPUT_RECEIVED"
    PROCESSING = "PROCESSING"
    EXTRACTING = "EXTRACTING"
    NORMALIZING = "NORMALIZING"
    RETRIEVING = "RETRIEVING"
    AI_ANALYSIS = "AI_ANALYSIS"
    SAFETY_CHECK = "SAFETY_CHECK"
    TRIAGE_DRAFT_READY = "TRIAGE_DRAFT_READY"
    REVIEW_PENDING = "REVIEW_PENDING"
    REVIEWED = "REVIEWED"
    ESCALATED = "ESCALATED"
    REFERRED = "REFERRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
