"""Add async_tasks table

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-21 22:20:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_version', sa.Integer(), nullable=False, server_default=sa.text('1')),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('case_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('causation_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False, server_default=sa.text("'PENDING'")),
    sa.Column('attempt_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('max_attempts', sa.Integer(), nullable=False, server_default=sa.text('3')),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_category', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_async_tasks_idempotency')
    )
    op.create_index('ix_async_tasks_case', 'async_tasks', ['case_id'], unique=False)
    op.create_index('ix_async_tasks_pending', 'async_tasks', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_async_tasks_running', 'async_tasks', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'RUNNING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_async_tasks_running', table_name='async_tasks', postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_index('ix_async_tasks_pending', table_name='async_tasks', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_async_tasks_case', table_name='async_tasks')
    op.drop_table('async_tasks')
    # ### end Alembic commands ###
